set -o errexit
set -o pipefail

tshark \
  -r "Data/B3/BinaryUmdf.v1.8/SecurityDefinitionMessage.pcap" \
  -X "lua_script:B3/B3_Equities_BinaryUmdf_Sbe_v1_8_Dissector.lua" \
  -T json \
  | jq '.[0]._source.layers["b3.equities.binaryumdf.sbe.v1.8.lua"]' \
  > B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json

grep "b3.equities.binaryumdf.sbe.v1.8.securityid" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.securityexchange" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.securityidsource" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.securitygroup" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.symbol" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.securityupdateaction" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.securitytype" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.securitysubtype" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.totnorelatedsym" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.minpriceincrementoptional" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.strikeprice" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.contractmultiplier" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.pricedivisor" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.securityvaliditytimestamp" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.nosharesissued" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.clearinghouseid" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.minorderqty" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.maxorderqty" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.minlotsize" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.mintradevol" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.corporateactioneventid" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.issuedate" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.maturitydate" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.countryofissue" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.startdate" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.enddate" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.settltype" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.settldate" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.dateddate" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.isinnumber" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.asset" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.cficode" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.currency" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.strikecurrency" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.settlcurrency" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.securitystrategytype" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.lottype" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.ticksizedenominator" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.product" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.exercisestyle" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.putorcall" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.pricetypepricetypeoptional" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.marketsegmentid" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.governanceindicator" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.securitymatchtype" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.lastfragment" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.multilegmodel" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.multilegpricemethod" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
grep "b3.equities.binaryumdf.sbe.v1.8.mincrossqty" B3.Equities.BinaryUmdf.Sbe.v1.8.SecurityDefinitionMessage.json
