version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:2021.04

jobs:
  test-in-docker:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: "Setup docker environment"
          command: sudo apt-get update && sudo apt-get install -y tshark
      - run:
          name: "Setup PATH environment variable"
          command: export PATH=/usr/local/bin:$PATH
      - run:
          name: "Clone OMI data"
          command: git clone --depth=1 https://github.com/Open-Markets-Initiative/Data.git
      - run:
          name: "Running Tests"
          command: bash -x Test.sh

workflows:
  test-in-docker:
    jobs:
      - test-in-docker

