name: Build Image

on:
  push:
    branches: [ main ]
    paths: [ '.github/docker/tshark-test.Dockerfile' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/open-markets-initiative/wireshark-lua-tshark:latest -f .github/docker/tshark-test.Dockerfile .

      - name: Push image
        run: docker push ghcr.io/open-markets-initiative/wireshark-lua-tshark:latest


